package org.parkjg20.specificationbuilder.application.board.post.usecase

import org.parkjg20.specificationbuilder.application.board.post.dto.BoardPostDto
import org.parkjg20.specificationbuilder.application.board.post.dto.BoardPostFilterDto
import org.parkjg20.specificationbuilder.application.board.usecase.GetManyUsingPaginationUseCase

interface BoardPostGetManyUsingPaginationUseCase: GetManyUsingPaginationUseCase<BoardPostFilterDto, BoardPostDto>